[package]
name = "lazyscript"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
arboard = "3.6.1"
base64 = "0.22.1"
clap = { version = "4.6.1", features = ["derive"] }
nix = { version = "0.31.3", features = ["signal"] }
notify = "8.2.0"
portable-pty = "0.9.0"
ratatui = "0.30.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.150", features = ["preserve_order"] }
tokio = { version = "1.52.3", features = ["full"] }
vt100 = "0.16.2"
